### ISSUE TITLE
[idea] show visual diff when snapshots do not match

### ISSUE THREAD

**Issue by sibelius** [guigrpa/jest-html#2]
we could show a visual diff to show where the snapshot diverge

using this https://github.com/Huddle/Resemble.js or another lib

**Comment by guigrpa** [comment]
That'd be really useful. I wonder though what the best flow would be:

1. Jest tells the user that a snapshot mismatch occurred
2. The user confirms the new snapshot, and Jest writes it to file
3. Assuming jest-html is running, it detects the file change, backs up its previous version of the snapshot (keeping it in a `baseline` field or something of the sort) and pushes the new data to the client

At the very least, the client could then show the before/after versions of the HTML snapshots. For Resemble, you'd need to convert those to images somehow (any idea?). For the time being, I'd stick to the simpler case.

**Comment by guigrpa** [comment]
@sibelius In case you're interested, version 1.3.1 implements the initial approach I drafted in my previous comment.

**Comment by sibelius** [comment]
Tks
