### ISSUE TITLE
snapshotSerializers doesn't seem to be adding HTML preview

### ISSUE THREAD

**Issue by digiguru** [guigrpa/jest-html#4]
I have setup my project as specified in the readme, adding this:

```"snapshotSerializers": ["<rootDir>/node_modules/jest-html"],```

But it seems that in your examples it includes HTML PREVIEW lines as follows 

```------------HTML PREVIEW---------------```

eg - https://github.com/guigrpa/jest-html/blob/master/test/exampleSnapshots/a/010-%C3%A1pp.test.js.snap#L139

however whenever I re-update my tests it fails to produce such a line in the output.

Is there a way to debug the output so I can understand whats going wrong?

**Comment by digiguru** [comment]
Oh actually I realised you can't do the update from jest-html - so you need to run 

```jest -u```
or
```npm run jest -- -u```

and not 

```jest-html -u```

Apologies

**Comment by guigrpa** [comment]
Glad you figured it out! Maybe we should add a line to the docs explaining that.

**Comment by xmorell** [comment]
This is the first time I'm creating snapshots, so maybe I say something stupid.

I am creating the snapshots automatically with "npm test -- -u"

But after that I am writting at the start the line "------------HTML PREVIEW---------------", is this how it is supposed to work?

**Comment by guigrpa** [comment]
If you see that `HTML PREVIEW` line, it means `jest-html` is running. Could you please share one of the (smallish) snapshots, to see that they're in good shape?
