### ISSUE TITLE
How can I use this with create-react-app?

### ISSUE THREAD

**Issue by jaredtmartin** [guigrpa/jest-html#9]
Would love to use this project, but I'm not sure how to configure the serializer with an app created with create-react-app

**Comment by jaredtmartin** [comment]
Sorry, I was under the impression I couldn't configure jest via package.json. Although create-react-app does limit jest configuration, it does work with snapshotSerializers.  This package works great with create-react-app!  Thanks a lot!

**Comment by guigrpa** [comment]
Good to know, thanks for reporting!
